name: CMake

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  c:
    strategy:
      matrix:
        os: [
          # ubuntu-latest,
          # macos-latest,
            windows-latest
        ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        id: checkout

      - name: Configure CMake
        if: ${{steps.checkout.outcome == 'success'}}
        id: configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        if: ${{steps.configure.outcome == 'success'}}
        id: build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Distribute
        if: ${{steps.build.outcome == 'success'}}
        id: install
        run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}/dist

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Store wheel
        if: ${{steps.install.outcome == 'success'}}
        uses: actions/upload-artifact@v2
        with:
          name: native (${{ matrix.os }})
          path: ${{github.workspace}}/dist
      
